name: PDF to HTML

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            ghostscript

      - name: Convert PDF to HTML
        run: |
          gs -dNOPAUSE -dBATCH -sDEVICE=html \
             -dFirstPage=1 -dLastPage=1 \
             -sOutputFile=index.html \
             my-file.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          publish_dir: ./
